---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - subscription.yaml
  - nexus-cr.yaml
  - route.yaml
  - docker-repository-route.yaml
  - docker-repository-service.yaml

