kind: NexusRepo
apiVersion: sonatype.com/v1alpha1
metadata:
  name: example-nexusrepo
  namespace: nexus
spec:
  config:
    data: null
    enabled: false
    mountPath: /sonatype-nexus-conf
  deployment:
    additionalContainers: null
    additionalVolumeMounts: null
    additionalVolumes: null
    annotations: {}
    initContainers: null
    postStart:
      command: null
    preStart:
      command: null
    terminationGracePeriodSeconds: 120
  deploymentStrategy:
    type: Recreate
  ingress:
    annotations: {}
    enabled: false
    path: /
    rules: null
    tls:
      enabled: true
      secretName: nexus-tls
  nexus:
    dockerPort: 5003
    env:
      - name: INSTALL4J_ADD_VM_PARAMS
        value: >-
          -Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M
          -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    hostAliases: []
    imageName: >-
      registry.connect.redhat.com/sonatype/nexus-repository-manager@sha256:06fe31f40ff3fd7556fc7b8f6b2efe80ada1d9079ec9aaad60d1fdc0ee0677f0
    imagePullPolicy: IfNotPresent
    imagePullSecret: ''
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    nexusPort: 8081
    podAnnotations: {}
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 30
      path: /
      periodSeconds: 30
    resources: {}
    securityContext: {}
    service:
      type: NodePort
  nexusProxyRoute:
    annotations: null
    enabled: false
    labels: null
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    storageSize: 8Gi
  replicaCount: 1
  secret:
    data: null
    enabled: false
    mountPath: /etc/secret-volume
    readOnly: true
  service:
    annotations: {}
    enabled: false
    labels: {}
    ports:
      - name: nexus-service
        port: 80
        targetPort: 80
  statefulset:
    enabled: false
  tolerations: []
